name: Enviar recordatorios de agenda

on:
  schedule:
    # Ajusta el cron según tus necesidades
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script de recordatorios
        run: node index.js
